title: Abdul Mohammed # your name (or website title) here
logo: "/images/my_final_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Researcher with experience in Medical Imaging and Healthcare Analytics.
  Worked in an Analyst capacity at the world's larget Oil and Gas company; Saudi Aramco.
  <br>
  Robotics and AI Graduate from the University of Maryland - College Park
  <br><br>
  Currently focused on learning and building projects in Natural Language Processing (NLP).
  Passionate about solving challenges that have a significant impact on society.
  <br><br>
  What Makes Me Unique: My "get things done" attitude sets me apart. 
  Need a groundbreaking research idea quickly or a last-minute Costco run? Count on me to deliver with efficiency and enthusiasm.
  Master's in pulling All-nighters to get things moving

  <br><br>
  Apart from work, I love to invest in watching Tv shows that reflect on intellect and passion for bringing innovation.
  Favourite Quote " I don't play the odds, I play the man" --Harvey Specter(Suits)  
  <br><br>
  
  <a href="https://www.linkedin.com/in/anm24/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

