title: Abdul Mohammed # your name (or website title) here

logo: "/images/my_final_pic.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Researcher with experience in Medical Imaging and Healthcare Analytics. Worked as an Analyst at the world's largest Oil and Gas company; Saudi Aramco.
  <br><br>
  Robotics and AI Graduate from the University of Maryland - College Park.
  <br><br>
  Currently focused on learning and building projects in Natural Language Processing (NLP). Passionate about solving challenges that have a significant impact on society.
  <br><br>
  What Makes Me Unique: My "get things done" attitude sets me apart. Need a groundbreaking research idea quickly or a last-minute Costco run? Count on me to deliver with efficiency and enthusiasm.
  <br><br>
  Apart from work, I love to invest in watching TV shows that reflect on intellect and passion for bringing innovation.

  Favorite Quote: "I don't play the odds, I play the man" - Harvey Specter (Suits)

  <a href="https://www.linkedin.com/in/anm24/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
